name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H vibecheckapi.01z.io >> ~/.ssh/known_hosts

    - name: Deploy
      run: |
        ssh root@vibecheckapi.01z.io 'cd /var/www/vibecheckapi/ && git pull'
