name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.89.0
      with:
        components: clippy

    - name: Info
      run: |
        hostname
        cargo version
        cargo clippy --version

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          api/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('api/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose
      working-directory: api

    - name: Run tests
      run: cargo test --verbose
      working-directory: api

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      working-directory: api
